
development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: jssliuder_dev
  pool:     5
  username: root
  password: root
  template: template0
  port: 5432

# test:
#   host: localhost
#   adapter:  postgresql
#   host:     localhost
#   encoding: unicode
#   database: nested_form_test
#   pool:     5
#   username: root
#   password: root
#   template: template0

# production:
#   adapter:  postgresql
#   host:     localhost
#   encoding: unicode
#   database: nested_form_production
#   pool:     5
#   username: root
#   password: root
#   template: template0
